version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    command: ["--bind_ip", "0.0.0.0"]
  app:
    container_name: desafioze-app
    build: .
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    links:
      - mongodb